'use strict';

const ROLES = {
  ADMIN: 'ADMIN',
  EMPLOYEE: 'EMPLOYEE',
  FINANCE: 'FINANCE',
};

const PERMISSIONS = {
  VIEW_DASHBOARD: [ROLES.ADMIN, ROLES.EMPLOYEE, ROLES.FINANCE],
  MANAGE_BOOKINGS: [ROLES.ADMIN, ROLES.EMPLOYEE],
  EDIT_FINANCE: [ROLES.ADMIN, ROLES.FINANCE],
  MANAGE_USERS: [ROLES.ADMIN],
  ARCHIVE_BOOKINGS: [ROLES.ADMIN],
  VIEW_REPORTS: [ROLES.ADMIN, ROLES.FINANCE],
};

const STAGES = {
  PARKING_LOT: 'PARKING_LOT',
  ON_ROAD: 'ON_ROAD',
  UNLOAD: 'UNLOAD',
  DONE: 'DONE',
  ARCHIVED: 'ARCHIVED',
};

const STAGE_LABELS = {
  [STAGES.PARKING_LOT]: 'Parking Lot',
  [STAGES.ON_ROAD]: 'On Road',
  [STAGES.UNLOAD]: 'Unload',
  [STAGES.DONE]: 'Done',
  [STAGES.ARCHIVED]: 'Archived',
};

const STAGE_ORDER = [
  STAGES.PARKING_LOT,
  STAGES.ON_ROAD,
  STAGES.UNLOAD,
  STAGES.DONE,
  STAGES.ARCHIVED,
];

const VALID_TRANSITIONS = {
  [STAGES.PARKING_LOT]: [STAGES.ON_ROAD],
  [STAGES.ON_ROAD]: [STAGES.UNLOAD],
  [STAGES.UNLOAD]: [STAGES.DONE],
  [STAGES.DONE]: [STAGES.ARCHIVED],
  [STAGES.ARCHIVED]: [],
};

const STAGE_COLORS = {
  [STAGES.PARKING_LOT]: 'secondary',
  [STAGES.ON_ROAD]: 'primary',
  [STAGES.UNLOAD]: 'warning',
  [STAGES.DONE]: 'success',
  [STAGES.ARCHIVED]: 'dark',
};

module.exports = {
  ROLES,
  PERMISSIONS,
  STAGES,
  STAGE_LABELS,
  STAGE_ORDER,
  VALID_TRANSITIONS,
  STAGE_COLORS,
};
